# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=512)),
                ('title', models.TextField()),
                ('duration', models.IntegerField(null=True)),
                ('audio_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400)),
            ],
        ),
    ]
